# this is comment
# platforms

shortplatforms:

longplatforms:
  - 0
    380
    10

  - 1430
    380
    10

Xobstacles:
  - 400
    320

  - 700
    320

  - 1000
    320

Yobstacles:
  - 300
    300
    3