# this is comment
# platforms

shortplatforms:
  - 600
    300

  - 900
    200

longplatforms:
  - 0
    380
    10

  - 1630
    280
    10

  - 3200
    400
    10

Xobstacles:
  - 2000
    220

  - 3300
    320

Yobstacles:
  - 1300
    0
    4